In [1]:
print("hello world")


hello world


In [3]:
!pip3 install numpy

In [4]:
import numpy as np

In [5]:
arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim

2

In [9]:
arr.shape

(2, 3)

In [10]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [11]:
c = np.zeros((3, 4))

In [12]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4. 2.0]])

In [25]:
arr

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]])

In [ ]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4. 2.0]])

In [23]:
arr

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]])

In [24]:
arr[1::2, :3:2]

array([[5, 4]])

In [26]:
a = np.array([1, 2, 5, 3])

In [27]:
a+1

array([2, 3, 6, 4])

In [28]:
a+3

array([4, 5, 8, 6])